number1=int(input("Enter number 1 : "))
number2=int(input("Enter number 2 : "))
number3=int(input("Enter number 3 : "))
print("use equal to :",number1==number2)
print("use not equal to :",number1!=number2)
print("use to greter then : ",number1>number2)
print("use lese then : ",number1<number2)
print("use greter then equal to ",number1>=number2)
print("use lese then equal to ",number1<=number2)
print("logical operator and  :",number1==number2 and number2==number3 )
print("logical operator or : ",number1==number2 or number2==number3 or number3==number1)
print("logical operatoe not : ",    (number1==number2 or number2==number3))